name: relay
version: "1.0.0"
config-version: 2
profile: relay
model-paths: ["models"]
target-path: target
clean-targets: ["target", "dbt_packages"]
models:
  relay:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    utilities:
      +materialized: table
      +schema: marts
